---
title: "LandWeb_preamble"
author: ""
date: "09 December 2018"
output:
  pdf_document:
    keep_md: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE, message = FALSE, warning = FALSE, results = "hold")
if (!require("Require", quietly = TRUE)) {
  install.packages("Require")
  library(Require)
}
Require("SpaDES.core", require = FALSE, upgrade = FALSE)
Require("magrittr")
```

# Overview

Set up study areas and parameters for LandWeb simulations.

# Parameters

Provide a summary of user-visible parameters.

```{r moduleParams, echo = FALSE, eval = TRUE}
df_params <- SpaDES.core::moduleParams("LandWeb_preamble", "..")
knitr::kable(df_params) %>%
  kableExtra::kable_styling(latex_options = "scale_down", full_width = TRUE)
```

# Data dependencies

## Input data

Description of the module inputs.

```{r moduleInputs, echo = FALSE, eval = TRUE}
df_inputs <- SpaDES.core::moduleInputs("LandWeb_preamble", "..")
knitr::kable(df_inputs) %>%
  kableExtra::kable_styling(latex_options = "scale_down", full_width = TRUE)
```

## Output data

Description of the module outputs.

```{r moduleOutputs, echo = FALSE, eval = TRUE}
df_outputs <- SpaDES.core::moduleOutputs("LandWeb_preamble", "..")
knitr::kable(df_outputs) %>%
  kableExtra::kable_styling(latex_options = "scale_down", full_width = TRUE)
```

# Links to other modules

Originally developed for use with the LandR Biomass suite of modules, with LandMine fire model.
